title: SE Conference Deadlines
description: Countdowns to top SE conference deadlines
author: jncsw

domain: "jncsw.github.io"
baseurl: ""

twitter_hashtag: software_engineering
github_username: jncsw
github_repo: se-deadlines

markdown: kramdown
ga_id:

include: ['_pages']
