title: SE Conference Deadlines
description: Countdowns to selected SE conference deadlines
author: jncsw

domain: "https://github.com/jncsw/se-deadlines/"
baseurl: "/se-deadlines/"

#twitter_hashtag: software_engineering
github_username: jncsw
github_repo: se-deadlines

markdown: kramdown
ga_id:

include: ['_pages']
